"""fix player.alive type

Revision ID: 0a8de3ca86aa
Revises: 210956ae62f3
Create Date: 2024-05-09 15:07:47.171082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8de3ca86aa'
down_revision: Union[str, None] = '210956ae62f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'alive',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using="alive::boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'alive',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
