"""add timezone info

Revision ID: 210956ae62f3
Revises: 05126ce743eb
Create Date: 2024-05-08 21:58:19.062016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210956ae62f3'
down_revision: Union[str, None] = '05126ce743eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'started_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="started_at::timestamp without time zone")
    op.alter_column('games', 'finish_at',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=True,
               postgresql_using="finish_at::timestamp without time zone")
    op.alter_column('games', 'is_active',
               existing_type=sa.VARCHAR(),
               type_=sa.Boolean(),
               existing_nullable=False,
               postgresql_using="is_active::boolean")
    op.alter_column('games', 'last_turn',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using="last_turn::integer")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'last_turn',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('games', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('games', 'finish_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('games', 'started_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
