"""Mixins for BaseModel

Revision ID: 39e3fef8b3ec
Revises: 8ad0bb5915d6
Create Date: 2024-05-07 16:08:46.394382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e3fef8b3ec'
down_revision: Union[str, None] = '8ad0bb5915d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
