"""add settsettings table

Revision ID: c396cc943c9a
Revises: af5ac0bc8ec4
Create Date: 2024-05-15 22:57:07.806453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c396cc943c9a'
down_revision: Union[str, None] = 'af5ac0bc8ec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('turn_timer', sa.Integer(), nullable=False),
    sa.Column('turn_counter', sa.Integer(), nullable=False),
    sa.Column('player_balance', sa.Integer(), nullable=False),
    sa.Column('shares_minimal_price', sa.Integer(), nullable=False),
    sa.Column('shares_maximum_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_settings')
    # ### end Alembic commands ###
