"""add unique rule

Revision ID: ee727c04750b
Revises: c396cc943c9a
Create Date: 2024-05-16 12:52:50.968072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee727c04750b'
down_revision: Union[str, None] = 'c396cc943c9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shares', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shares', type_='unique')
    # ### end Alembic commands ###
