debug: true
web:
  host: 127.0.0.1
  port: 8000
admin:
  telegram_id: 123
  nickname: smdoff
  first_name: Maxim
  password: 123
  is_admin: True
sentry:
  dsn:
  env: dev
database:
  host: localhost
  port: 5432
  user: postgres
  password: DB_PASSWORD
  database: kts
bot:
  token: BOT_TOKEN
store: {}
