debug: true
web:
  host: 127.0.0.1
  port: 8000
admin:
  telegram_id: BOT_ADMIN_ID
  nickname: BOT_ADMIN_USERNAME
  first_name: BOT_ADMIN_FIRST_NAME
  password: BOT_ADMIN_PASSWORD
sentry:
  dsn:
  env: dev
database:
  host: POSTGRES_HOST
  port: POSTGRES_PORT
  user: POSTGRES_USER
  password: POSTGRES_PASSWORD
  database: POSTGRES_DB
bot:
  token: BOT_TOKEN
store: {}
