debug: true
web:
  host: 127.0.0.1
  port: 8000
admin:
  email: pumpbro@gmail.com
  password: 123
sentry:
  dsn:
  env: dev
database:
  host: localhost
  port: 5432
  user: postgres
  password: DB_PASSWORD
  database: kts
bot:
  token: BOT_TOKEN
store: {}
